### ISSUE TITLE
bug in read_data.py on PageMetadata =>  str fonction (categoryNames)

### ISSUE THREAD

**Issue by arevuzDisaitek** [TREMA-UNH/trec-car-tools#26]
The fonction `def __str__(self):` in the class `PageMetadata` crash on file without categoryNames.

There is an error in the test before getting categoryNames, it should be `if self.categoryNames is None` and not `if self.redirectNames is None`.

```
    def __str__(self):
        redirStr = ("" if self.redirectNames is None else (" redirected = "+", ".join([name for name in self.redirectNames])))
        disamStr = ("" if self.disambiguationNames is None else (" disambiguated = "+", ".join([name for name in self.disambiguationNames])))
        catStr = ("" if self.redirectNames is None else (" categories = "+", ".join([name for name in self.categoryNames]))) ## HERE
        inlinkStr = ("" if self.inlinkIds is None else (" inlinks = "+", ".join([name for name in self.inlinkIds])))
        # inlinkAnchorStr = str (self.inlinkAnchors)
        inlinkAnchorStr = ("" if self.inlinkAnchors is None else \
                                (" inlinkAnchors = "+", ".join( \
                                    [ ("%s: %d" % (name, freq)) for (name, freq) in self.inlinkAnchors] \
                                    # [ ("%s: " % (name)) for (name, freq) in self.inlinkAnchors] \
                                )))
        return  "%s \n%s \n%s \n%s \n%s\n" % (redirStr, disamStr, catStr, inlinkStr, inlinkAnchorStr)
```

I find it will i was trying to read the last release of the TRECCAR dataset, so I am confuse...

This bug stay on the git for 6 months (last commit on read_data), so no one had this problem before me...?
Am I using the wrong dataset and all the files must have categoryNames? 
or do most users not use the python version of the tool?

**Comment by bgamari** [comment]
@laura-dietz, did you see this?

**Comment by laura-dietz** [comment]
@arevuzDisaitek Thanks for bringing this up!

Would you be interested in submitting a pull request?

As an explanation: I think only few people use the python bindings, and even fewer are working with category information.

**Comment by arevuzDisaitek** [comment]
@laura-dietz, I did

**Comment by laura-dietz** [comment]
@arevuzDisaitek (Sorry, my bad) Thank you very much!!
