### ISSUE TITLE
Paragraph-Dataset 2.0 cannot be loaded in java

### ISSUE THREAD

**Issue by Sunkua** [TREMA-UNH/trec-car-tools#28]
I am facing an issue when trying to read the paragraph-corpus-dataset 2.0.
The code to read the data looks like the one given in the examples:

`final FileInputStream fileInputStream = new FileInputStream(new File(path));
    for(Data.Paragraph p : DeserializeData.iterableParagraphs(fileInputStream)) {
      System.out.println(p);
    }`

When the program tries to load the first paragraph it quits with the following exception:

> java.lang.NullPointerException
	at edu.unh.cs.treccar_v2.read_data.DeserializeData.paragraphFromCbor(DeserializeData.java:294)
	at edu.unh.cs.treccar_v2.read_data.DeserializeData.access$100(DeserializeData.java:14)
	at edu.unh.cs.treccar_v2.read_data.DeserializeData$1ParagraphIterator.parseItem(DeserializeData.java:142)
	at edu.unh.cs.treccar_v2.read_data.DeserializeData$1ParagraphIterator.parseItem(DeserializeData.java:137)
	at edu.unh.cs.treccar_v2.read_data.CborListWithHeaderIterator.next(CborListWithHeaderIterator.java:53)
	at ...

The reader seems to expect a tag for each item in the cbor (see the assert in DeserializeData.pageFromCbor()) which is currently null for each array in the given DataItem.

I use the maven-dependencies in version 2.0 and tried different java-version from 1.8 to 11.
The data is readable in Python without any issue.

**Comment by laura-dietz** [comment]
Hi Paul,
    
    
    thanks for your interest.
    
    
    My hunch is that this is due to a
      version conflict. Can you tell me which version of trec-car-tools
      you are using?  (You can either paste the maven dependency you are
      using or the commit if you were checking out the sources)
    
    
    Best,
      Laura
    
    
    
    
    
    On 5/6/19 6:58 PM, Paul Grundmann
      wrote:
    
    
      
      I am facing an issue when trying to read the
        paragraph-corpus-dataset 2.0.
        The code to read the data looks like the one given in the
        examples:
      final FileInputStream fileInputStream = new
          FileInputStream(new File(path)); for(Data.Paragraph p :
          DeserializeData.iterableParagraphs(fileInputStream)) {
          System.out.println(p); }
      When the program tries to load the first paragraph it quits
        with the following exception:
      
        java.lang.NullPointerException
          at
edu.unh.cs.treccar_v2.read_data.DeserializeData.paragraphFromCbor(DeserializeData.java:294)
          at
edu.unh.cs.treccar_v2.read_data.DeserializeData.access$100(DeserializeData.java:14)
          at
edu.unh.cs.treccar_v2.read_data.DeserializeData$1ParagraphIterator.parseItem(DeserializeData.java:142)
          at
edu.unh.cs.treccar_v2.read_data.DeserializeData$1ParagraphIterator.parseItem(DeserializeData.java:137)
          at
edu.unh.cs.treccar_v2.read_data.CborListWithHeaderIterator.next(CborListWithHeaderIterator.java:53)
          at ...
      
      The reader seems to expect a tag for each item in the cbor (see
        the assert in DeserializeData.pageFromCbor()) which is currently
        null for each array in the given DataItem.
      I use the maven-dependencies in version 2.0 and tried different
        java-version from 1.8 to 11.
        The data is readable in Python without any issue.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/TREMA-UNH/trec-car-tools/issues/28",
"url": "https://github.com/TREMA-UNH/trec-car-tools/issues/28",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Sunkua** [comment]
I am currently using version 2.0 from the maven repository:

```xml   
<dependency>
      <groupId>com.github.TREMA-UNH</groupId>
      <artifactId>trec-car-tools-java</artifactId>
      <version>2.0</version>
</dependency>"
```

**Comment by laura-dietz** [comment]
I don't think 2.0 is a valid version
      number
    
    
    Try this and let me know if this works.
    
    
    
    
      <repositories>
    <repository>
        <id>jitpack.io</id>
        <url>https://jitpack.io</url>
    </repository>
</repositories>

<dependencies>
   <dependency>
        <groupId>com.github.TREMA-UNH</groupId>
        <artifactId>trec-car-tools-java</artifactId>
        <version>15</version>
    </dependency>
    <dependency>
        <groupId>co.nstant.in</groupId>
        <artifactId>cbor</artifactId>
        <version>RELEASE</version>
    </dependency>

    
    [...]
    
    
    
    
    
    I am worried that one page has a
      different version number on it. Can you tell me which page you got
      the wrong info from?
    
    
    Best,
      Laura
    
    
    
    
    
    
    
    On 5/7/19 11:32 AM, Paul Grundmann
      wrote:
    
    
      
      I am currently using version 2.0 from the maven repository:
      
        <dependency>
      <groupId>com.github.TREMA-UNH</groupId>
      <artifactId>trec-car-tools-java</artifactId>
      <version>2.0</version>
</dependency>"
      
      —
        You are receiving this because you commented.
        Reply to this email directly, view it on GitHub, or mute the thread.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/TREMA-UNH/trec-car-tools/issues/28#issuecomment-490007789",
"url": "https://github.com/TREMA-UNH/trec-car-tools/issues/28#issuecomment-490007789",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Sunkua** [comment]
I get exactly the same error. Version 2.0 is written in the readme in the master branch of this project.

**Comment by laura-dietz** [comment]
Usually you get serialization errors
      when you are
    - trying to load a cbor file with pages
      with the paragraph iterator (or vice versa)
    - load a data file from a new version
      with out-of-date bindings
    
    
    While we don't give guarantees, usually
      a newer version can still open old data files.
    
    
    Somehow, my hunch is that you are still
      using an out of date language bindings, because a more recent
      version would give you explicit warnings when the versions don't
      match or when you open a paragraph file with the page reader. 
      (Unfortunately maven/java only consider versions at compile/build
      time, but not at run time)
    
    
    Another source might be a version
      conflict of the con.stant.in cbor bindings.
    
    
    
    
    Your ealier stacktrace contained a
      NullPointerException at  DeserializeData.java:294
    Do you have the same line number with
      the new version (15) ?
    
    
     I am asking, because that line cannot
      cause an NPE in v15 --- if the line number changed, we can at
      least exclude that a ghost version is still in your run time
      system.
    
    
    
    
    
    Laura
    
    
    
    BTW: I updated the readme.
    P.S. Thanks for your patience!
    
    
    
    
    
    
    
    
    
    On 5/7/19 12:17 PM, Paul Grundmann
      wrote:
    
    
      
      I get exactly the same error. Version 2.0 is written in the
        readme in the master branch of this project.
      —
        You are receiving this because you commented.
        Reply to this email directly, view it on GitHub, or mute the thread.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/TREMA-UNH/trec-car-tools/issues/28#issuecomment-490022562",
"url": "https://github.com/TREMA-UNH/trec-car-tools/issues/28#issuecomment-490022562",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Sunkua** [comment]
OK i think i fixed the error. I found the java project for the current version here on Github and could remove the line (still the assert at l. 320) which caused the error. Without the assert everything seems to behave the right way. Perhaps something has changed concerning the tags which seem to be null of the DataItem from Version 1.5 to 2.0. 

Thank you :)

**Comment by laura-dietz** [comment]
Paul,
    
    
    I really think you got an out of date
      version of the language bindings.
    
    
    Especially the fact that you were still
      getting the error message in the wrong line number is highly
      suspicious.
    
    
    
    
    We have been using the v2.0 format and
      new language bindings for more than one year. My students are
      using it as well. They don't get this error message.
    
    
    
    
    When we switched to jitpack we had to
      move the java code to a separate repository -- I wonder whether
      you picked up old source code from the old location. (Although I
      am wondering how you were using the maven dependency in this
      case).
    
    
    Laura
    
    
    
    
    
    
    
    On 5/7/19 12:53 PM, Paul Grundmann
      wrote:
    
    
      
      OK i think i fixed the error. I found the java project for the
        current version here on Github and could remove the line (still
        the assert at l. 320) which caused the error. Without the assert
        everything seems to behave the right way. Perhaps something has
        changed concerning the tags which seem to be null of the
        DataItem from Version 1.5 to 2.0.
      Thank you :)
      —
        You are receiving this because you commented.
        Reply to this email directly, view it on GitHub, or mute the thread.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/TREMA-UNH/trec-car-tools/issues/28#issuecomment-490031508",
"url": "https://github.com/TREMA-UNH/trec-car-tools/issues/28#issuecomment-490031508",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
