### ISSUE TITLE
cannot load test200 v2.0 in python

### ISSUE THREAD

**Issue by hlcr** [TREMA-UNH/trec-car-tools#29]
Hi, there.
I have followed the instruction. Use the following command to get data from the dataset, but failed.
`python test.py pages train.pages.cbor`

I get the following errors:

**Traceback (most recent call last):
  File "test.py", line 29, in <module>
    args.func(args)
  File "test.py", line 7, in dump_pages
    for p in iter_annotations(args.file):
  File "E:\PythonProject\TERC-CAR\trec_car\read_data.py", line 232, in iter_annotations
    yield Page.from_cbor(cbor.load(file))
  File "E:\PythonProject\TERC-CAR\trec_car\read_data.py", line 44, in from_cbor
    assert cbor[0] == 0 # tag
AssertionError**

Then I try to print out the binary data that I have read from the file, and I got this:

`['CAR', [0], [0, [[0, 'enwiki', 'en-US', '20161220', []]], 'trec-car v2.0', [], [[0, 'trec-car-import', '0b10a0342662c908f3198d79100796472918d30a', []]]]]
`

Is there anything wrong with my operation? Could anyone help me? thank you.

**Comment by laura-dietz** [comment]
Hi Hongli
    
    It looks like you are using an old version of the code.
    
    Through which way did you obtain the code?  (anaconda, pypi,
      github, ..?)  Maybe I still have an old version out there...
    
    
    In doubt, use this: https://github.com/TREMA-UNH/trec-car-tools
    Best,
      Laura
    
    
    
    
    
    
    
    On 6/12/19 4:44 AM, Hongli Chen wrote:
    
    
      
      Hi, there.
        I have followed the instruction. Use the following command to
        get data from the dataset, but failed.
        python test.py pages train.pages.cbor
      I get the following errors:
      Traceback (most recent call last):
          File "test.py", line 29, in 
          args.func(args)
          File "test.py", line 7, in dump_pages
          for p in iter_annotations(args.file):
          File "E:\PythonProject\TERC-CAR\trec_car\read_data.py", line
          232, in iter_annotations
          yield Page.from_cbor(cbor.load(file))
          File "E:\PythonProject\TERC-CAR\trec_car\read_data.py", line
          44, in from_cbor
          assert cbor[0] == 0 # tag
          AssertionError
      Then I try to print out the binary data that I have read from
        the file, and I got this:
      ['CAR', [0], [0, [[0, 'enwiki', 'en-US', '20161220',
          []]], 'trec-car v2.0', [], [[0, 'trec-car-import',
          '0b10a0342662c908f3198d79100796472918d30a', []]]]] 
      Is there anything wrong with my operation? Could anyone help
        me? thank you.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/TREMA-UNH/trec-car-tools/issues/29?email_source=notifications\u0026email_token=AAGLMNFUQVBR3I5H3GPZP3DP2CZPFA5CNFSM4HXGVK72YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GZABRAA",
"url": "https://github.com/TREMA-UNH/trec-car-tools/issues/29?email_source=notifications\u0026email_token=AAGLMNFUQVBR3I5H3GPZP3DP2CZPFA5CNFSM4HXGVK72YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GZABRAA",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by hlcr** [comment]
Thanks, Laura !
By following your suggestion, I finally read the data. 
If you could, please modify the Support Tools Link under the "Data Format Description" section on http://trec-car.cs.unh.edu/. 
The URL on the last line points to the v1.5 instead of the latest version.
