### ISSUE TITLE
moving to python>=3.6 and dropping typing requirement?

### ISSUE THREAD

**Issue by seanmacavaney** [TREMA-UNH/trec-car-tools#36]
Hi Laura, (cc: @cmacdonald)

Would you approve a PR that did the following:
 1. Removed support for python 3.5
 2. Dropped the pypi typing requirement

The reason being that from python 3.6 onward, typing is part of the standard library. The pypi package shadows the standard library version, and this leads to some annoying errors.

I don't think many people still use 3.5, so it wouldn't be a big loss. (And if they did, they could always use the previous version  of trec-car-tools from pypi.)

Thanks!
sean

**Comment by laura-dietz** [comment]
yes, but it needs to be a PR on the
      latest version (which also supports the additional info in the
      wiki2020 dump)
    
    
    Laura
    
    
    
    On 3/5/21 1:09 PM, seanmacavaney wrote:
    
    
      
      Hi Laura, (cc: @cmacdonald)
      Would you approve a PR that did the following:
      
        Removed support for python 3.5
        Dropped the pypi typing requirement
      
      The reason being that from python 3.6 onward, typing is part of
        the standard library. The pypi package shadows the standard
        library version, and this leads to some annoying errors.
      I don't think many people still use 3.5, so it wouldn't be a
        big loss. (And if they did, they could always use the previous
        version of trec-car-tools from pypi.)
      Thanks!
        sean
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/TREMA-UNH/trec-car-tools/issues/36",
"url": "https://github.com/TREMA-UNH/trec-car-tools/issues/36",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by cmacdonald** [comment]
Thanks for the fast resolution guys.
